project_name: jfa-go
release:
    github:
        owner: hrfee
        name: jfa-go
    name_template: "v{{.Version}}"
before:
  hooks:
    - go mod download
    - rm -rf data/web
    - mkdir -p data
    - cp -r static data/web
    - cp -r css data/web/
    - npm install
    - cp node_modules/a17t/dist/a17t.css data/web/css/
    - cp node_modules/remixicon/fonts/remixicon.css node_modules/remixicon/fonts/remixicon.woff2 data/web/css/
    - cp -r html data/
    - cp -r lang data/
    - python3 config/fixconfig.py -i config/config-base.json -o data/config-base.json
    - python3 config/generate_ini.py -i config/config-base.json -o data/config-default.ini
    - python3 mail/generate.py -o data/
    - python3 version.py {{.Version}} version.go
    - bash -c 'npx esbuild ts/*.ts ts/modules/*.ts --outdir=./data/web/js/ --minify'
    - go get -u github.com/swaggo/swag/cmd/swag
    - swag init -g main.go
builds:
    - dir: ./
      env:
        - CGO_ENABLED=0
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - arm
        - arm64
archives:
  - replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        amd64: x86_64
    files:
        - data/*
        - data/**/*
        - data/**/**/*
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "git-{{.ShortCommit}}"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
